# Generated by Django 4.0.3 on 2023-10-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales_rest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomobileVO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("sold", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="salesperson",
            name="employee_id",
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
