# Generated by Django 4.0.3 on 2023-10-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='employee_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
