# Generated by Django 4.0.3 on 2023-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_salesperson_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
