# Generated by Django 4.0.3 on 2023-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_rest", "0002_alter_status_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="vin",
            field=models.CharField(max_length=17),
        ),
    ]
